site_name: 闲番观察室
site_url: https://anime.maple-kaede.eu.org
theme: 
  name: material
  language: zh 
  logo: assets/history_edu.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: 开启深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: 关闭深色模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes 
    - toc.follow
    - navigation.footer
  
plugins:
  - privacy
  - search:
      lang: zh
  # - rss:
  #     match_path: .* 
  #     date_from_meta:
  #       as_creation: date

# extra:
#   social:
#     - icon: material/rss-box
#       link: /feed_rss_created.xml

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format