site_name: 闲番观察室
theme: 
  name: material
  language: zh 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes 
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true